M48
; DRILL file KiCad 10.0.1 date 2026-07-30T14:49:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-30T14:49:06+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X116.315Y-79.11
X116.315Y-84.89
T2
X177.278Y-118.185
X177.278Y-126.185
M30
