#include "sysview_tracing.h"

#if (defined(CONFIG_SYSVIEW_ENABLE) && CONFIG_SYSVIEW_ENABLE) || (defined(CONFIG_SEGGER_SYSVIEW_ENABLE) && CONFIG_SEGGER_SYSVIEW_ENABLE) || (defined(CONFIG_APPTRACE_SV_ENABLE) && CONFIG_APPTRACE_SV_ENABLE)
void sysview_init_markers(){
  SEGGER_SYSVIEW_NameResource(TASK_ACCEL_GYRO_DAQ_ID + 1, TASK_ACCEL_GYRO_DAQ_NAME);
  SEGGER_SYSVIEW_NameResource(TASK_ATTITUDE_ID + 1,       TASK_ATTITUDE_NAME);
  SEGGER_SYSVIEW_NameResource(TASK_BARO_DAQ_ID + 1,       TASK_BARO_DAQ_NAME);
  SEGGER_SYSVIEW_NameResource(TASK_MAG_DAQ_ID + 1,        TASK_MAG_DAQ_NAME);
  SEGGER_SYSVIEW_NameResource(TASK_BLE_VEC3_TRANS_ID + 1, TASK_BLE_VEC3_TRANS_NAME);
}
#endif
