; [platformio]
; build_dir = C:\Users\Cat\.platformio\build
[env:esp32-s3-SuperMini]
platform = espressif32
board = esp32-s3-supermini
framework = arduino

upload_port = COM8
monitor_port = COM8
monitor_speed = 115200
lib_deps = fastled/FastLED@^3.9.4
;monitor_dtr = 0
;monitor_rts = 1
